version: '3.7'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db